#!/usr/bin/env ruby
# frozen_string_literal: true

# Get the text of every PDF under --pdf-dir that doesn't already have output
# under --ocr-dir.
#
# Most PDFs are scans, and go to lib/ocr_mlx.py as a manifest; that script
# loads chandra once and does the inference, writing <stem>.md.  It writes each
# document straight to its final destination, so there's no staging step and no
# name mangling to undo -- two PDFs with the same basename in different year
# folders land in different output directories and never collide.
#
# PDFs in SFI drops (`kind: sfi` in metadata.yml) are mostly generated by a
# filing system rather than scanned, so their text is already in the file.
# Those get `pdftotext -layout`, written as <stem>.txt in the same place, and
# only fall back to chandra when they turn out to be scans.  Disclosures always
# get chandra, even the few with a text layer: filer.rb reads form labels like
# "Name of public official:", which chandra puts back on one line and
# pdftotext leaves wrapped across two.

require "etc"
require "fileutils"
require "json"
require "optparse"
require "parallel"
require "tmpdir"
require_relative "drops"

opts = {
  pdf_dir: "input/pdfs",
  ocr_dir: "input/ocr",
  metadata: "metadata.yml",
  model: File.expand_path("../models/chandra-mlx-4bit", __dir__),
  batch_size: 8,
  limit: nil,
  dry_run: false,
}

OptionParser.new do |o|
  o.banner = "usage: ocr.rb [options]"
  o.on("--pdf-dir DIR")      { |v| opts[:pdf_dir] = v }
  o.on("--ocr-dir DIR")      { |v| opts[:ocr_dir] = v }
  o.on("--metadata FILE", "drop metadata, for each drop's kind") { |v| opts[:metadata] = v }
  o.on("--model DIR", "converted MLX model (see `make ocr-model`)") { |v| opts[:model] = v }
  o.on("--batch-size N", Integer, "pages per inference batch") { |v| opts[:batch_size] = v }
  o.on("--limit N", Integer, "only process the first N pending PDFs") { |v| opts[:limit] = v }
  o.on("--dry-run", "list what would be processed, then stop") { opts[:dry_run] = true }
end.parse!

PDF_DIR = File.expand_path(opts[:pdf_dir])
OCR_DIR = File.expand_path(opts[:ocr_dir])
DROPS = Drops.load(opts[:metadata])

# A page with fewer non-space characters than this has no text layer, i.e. it's
# a scanned image.  Every page has to clear it, not just the document on
# average: a typed cover letter stapled to a scanned form has plenty of text
# overall and still needs OCR.  It's deliberately low -- real pages can be
# short (most Boston SFIs end on a page of 26 characters), while scans come out
# at zero.
MIN_PAGE_CHARS = 10

# A PDF at <pdf_dir>/<drop>/<rel>.pdf gets its text in <ocr_dir>/<drop>/<rel>/.
# We keep <rel>'s subdirectories rather than flattening to the basename because
# basenames collide (91 of them in 2025-08-07-sec alone).
Job = Struct.new(:pdf, :dest_dir, :stem, keyword_init: true)

# Done means either kind of output exists.  Timestamps aren't compared: zips
# store local times with no zone, so a drop can extract PDFs dated hours in
# the future, and re-extracting a drop resets them anyway -- either way
# finished work would look stale.  To redo a PDF, delete its output.
def done?(dest_dir, stem)
  %w[md txt].any? { |ext| File.exist?(File.join(dest_dir, "#{stem}.#{ext}")) }
end

def sfi?(job)
  drop = job.pdf.delete_prefix("#{PDF_DIR}/").split("/").first
  Drops.kind(DROPS[drop]) == Drops::SFI
end

# The PDF's text layer, if every page has one; nil if any page is a scan or
# pdftotext can't read the file.  pdftotext ends every page with a form feed,
# so N pages split into N + 1 pieces, the last one empty.  The -1 matters: a
# plain split drops trailing empty strings, which would make an all-scan PDF
# look like it had no pages, and so no pages failing the test.
def text_layer(pdf)
  text = IO.popen(["pdftotext", "-q", "-layout", pdf, "-"], err: File::NULL, &:read)
  return nil unless $?.success?

  pages = text.force_encoding(Encoding::UTF_8).scrub.split("\f", -1)[0...-1]
  return nil if pages.empty? || pages.any? { |p| p.gsub(/\s/, "").length < MIN_PAGE_CHARS }

  pages.join("\n")
end

# Written under a temporary name and renamed into place, so a <stem>.txt that
# exists is always complete -- the same promise ocr_mlx.py keeps by writing the
# .md last.
def write_text(job, text)
  FileUtils.mkdir_p(job.dest_dir)
  dest = File.join(job.dest_dir, "#{job.stem}.txt")
  File.write("#{dest}.tmp", text)
  File.rename("#{dest}.tmp", dest)
end

pdfs = Dir.glob(File.join(PDF_DIR, "*", "**", "*.pdf"), File::FNM_CASEFOLD).sort

jobs = []
pdfs.each do |pdf|
  rel = pdf.delete_prefix("#{PDF_DIR}/")
  dest_dir = File.join(OCR_DIR, rel.delete_suffix(File.extname(rel)))
  stem = File.basename(pdf, ".*")
  next if done?(dest_dir, stem)

  jobs << Job.new(pdf: pdf, dest_dir: dest_dir, stem: stem)
end

jobs = jobs.first(opts[:limit]) if opts[:limit]

# pdftotext takes a few tens of milliseconds a document, so trying it costs
# little even on a dry run, and a dry run that couldn't say how much work is
# headed for chandra wouldn't be much use.  It's a subprocess, so threads are
# enough to keep every core busy.
sfi_jobs, ocr_jobs = jobs.partition { |job| sfi?(job) }
extracted = Parallel.map(sfi_jobs, in_threads: Etc.nprocessors) do |job|
  text = text_layer(job.pdf) or next false
  write_text(job, text) unless opts[:dry_run]
  true
end
ocr_jobs += sfi_jobs.zip(extracted).reject { |_, ok| ok }.map(&:first)
ocr_jobs.sort_by!(&:pdf)
text_count = extracted.count(true)

verb = opts[:dry_run] ? "would get" : "got"
puts "#{pdfs.size} PDF(s) found, #{jobs.size} needing text: " \
     "#{text_count} #{verb} it from pdftotext, #{ocr_jobs.size} need OCR"

if ocr_jobs.empty?
  puts "nothing to OCR"
  exit 0
end

if opts[:dry_run]
  ocr_jobs.each { |job| puts "  #{job.pdf.delete_prefix("#{PDF_DIR}/")}" }
  exit 0
end

unless File.directory?(opts[:model])
  abort "model not found at #{opts[:model]}; run `make ocr-model` first"
end

ok = false
Dir.mktmpdir("ocr-manifest") do |dir|
  manifest = File.join(dir, "jobs.json")
  File.write(manifest, JSON.generate(ocr_jobs.map(&:to_h)))

  cmd = [
    "uv", "run", "--quiet", "--python", "3.12",
    File.expand_path("ocr_mlx.py", __dir__),
    manifest,
    "--model", opts[:model],
    "--batch-size", opts[:batch_size].to_s,
  ]
  puts cmd.join(" ")
  ok = system(*cmd)
end

# ocr_mlx.py writes each document as it finishes and reports its own failures,
# so a non-zero exit still leaves completed work on disk.  Anything missing
# stays pending and gets retried on the next run.
unless ok
  warn "ocr_mlx.py exited non-zero; completed documents were still written"
  exit 1
end
